baseURL = '/'
languageCode = 'en-us'
theme = "hugo-tufte"

[params]
    contentTypeName = "posts"
    fullWidthTheme = false
    centerTheme = false
    favicon = "ggjhyt.ico"
    showLastUpdated = true
